version: 2.1

anchors:
  - workspace-root: &workspace-root ~/minhtest-app
  - &feature-branch-filter
    filters:
      branches:
        only: /^(?!master$).*/
  - &master-branch-filter
    filters:
      branches:
        only: /^master$/

executors:
  default-executor:
    docker:
      - image: cimg/go:1.15
    working_directory: *workspace-root

commands:
  attach-to-workspace:
    description: "Attach to the workspace"
    steps:
      - attach_workspace:
          at: *workspace-root
          
  run-tests:
    description: "Run tests"
    steps:
      - run:
          name: Run tests
          command: |
            go test -v

  deploy-to-heroku-via-git:
    description: "Deploy app to Heroku"
    parameters:
      app-name:
        description: the name of the heroku app to deploy to
        type: string
    steps:
      - run:
          name: Deploy app to Heroku
          command: |
            # get the current git commit hash
            CURRENT_COMMIT=$(git rev-parse HEAD)
            # deploy that version of the app to heroku
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/<< parameters.app-name >>.git $CURRENT_COMMIT:refs/heads/master
            
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Bundling go artifacts
          command: |
            go build -v
      - persist_to_workspace:
          root: *workspace-root
          paths:
            - .
  test:
    executor: default-executor
    steps:
      - attach-to-workspace
      - run-tests
  
  deploy-production:
    executor: default-executor
    working_directory: *workspace-root
    steps:
      - attach-to-workspace
      - deploy-to-heroku-via-git:
          app-name: yonomi-cloudwatch-drain

workflows:
  deploy:
    jobs:
      - build:
          context: org-global
          <<: *master-branch-filter
      - test:
          context: org-global
          requires:
            - build
      - deploy-production:
          context: org-global
          requires:
            - test